[[pages]]
path = "pages/news/20250318.py"
name = "20250318"
icon = "📰"

[[pages]]
path = "pages/news/20250503.py"
name = "20250503"
icon = "📰"

[[pages]]
path = "pages/news/20251015.py"
name = "20251015"
icon = "📰"
